market_microstructure:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      schema: main

    prod:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: optimum-bonbon-296801
      dataset: market_data
      location: asia-south1
      threads: 4
